schema: jahia-schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://jahia.localhost/modules/graphql
      headers:
        user-agent: JS GraphQL
        origin: https://jahia.localhost
        Authorization: Basic cm9vdDpyb290MTIzNA==
      introspect: true
